export const icons = {
    aonegame: require('../../assets/images/aonegame.png'),
    arrowleft:require('../../assets/images/arrowleft.png'),
    phone:require('../../assets/images/phone.png'),
    people:require('../../assets/images/people.png'),
    bankbuilding:require('../../assets/images/bankbuilding.png'),
    smartphonecall:require('../../assets/images/smartphonecall.png'),
    megaphone:require('../../assets/images/megaphone.png'),
    whatsapp:require('../../assets/images/whatsapp.png'),
    instagramlive:require('../../assets/images/instagramlive.png'),
    casino:require('../../assets/images/casino.png'),
    drawhistroy:require('../../assets/images/drawhistroy.png'),
    ticket:require('../../assets/images/ticket.png'),
    rechages:require('../../assets/images/rechages.png'),
    switch:require('../../assets/images/switch.png'),
    livechat:require('../../assets/images/livechat.png'),
    share:require('../../assets/images/share.png'),
    baazigaer:require('../../assets/images/baazigaer.png'),
}