import { version } from "react";

export const string = {
  a1onlinegame: 'A1 Online Games',
  enternumber: 'Enter Your Number',
  pleaseenter: 'Please enter your mobile number to receive a verification code.',
  login: 'LOGIN',
  forverification: "For verification, an OTP has been sent to",
  enterit: 'Enter it below.',
  verifi: 'VERIFY',
  wallet: 'Wallet Summary',
  yourcoins: 'YOUR COINS',
  blocked: 'BLOCKED COINS',
  recharge: 'Recharge',
  whitdraw: 'Withdraw',
  transactions: 'Transactions',
  notransactiontext: 'No Transactions History Found',
  rechargeyourwallet: 'Recharge your wallet for the flawlessly play.',
  amount: 'Amount',
  pay: 'PAY',
  Request: 'Request for withdraw money from wallet.',
  Requestfor: 'Request for withdraw money from wallet via UPI or Bank Detail',
  notewith: 'Note: Withdrawal process will take 10 to 15 min to complete.',
  editprofile: 'Edit Profile',
  upiidis: 'UPI Id is used to withdraw money from wallet to your back account.',
  save: 'Save',
  coins: 'Coins',
  option: 'Options',
  thisiscomm: 'This is common text',
  chat:'Chat Support',
  live:'Live Yantra Game',
  Livecasino:'Live Casino & Cricket Game',
  deraw:'Draw History',
  ticket:'Ticket Purchased History',
  rechargewith:'Recharge & Withdraw',
  Logout:'Logout',
  terms:'Terms & Cndition',
  version:'Version : 1.5',
  marketopentime:'Market open time 8 am market close time 11 pm'
}